data/src/main/sqldelight/tachiyomi/data/chapters.sq, data/src/main/sqldelight/tachiyomi/data/mangas.sq, data/src/main/sqldelight/tachiyomi/data/mangas_categories.sq
Set the lastModifiedAt default to 0 on insert, this way when syncing it doesn't mark chapter as unread.
For example:
Device A: has a manga with 79 chapter main device used for reading and more up to date.
Device B: haven't done any update library so it's stale, something like 78 chapter now when the user sync it will get the data from Device B as latest since on insert previously sets the current time. 
Device A: Marks the chapter that was read as unread.
Well another approach is to sync before library update, but with this changes it they don't have to sync before updating library.
=> refactor: db changes for syncing.

i18n/src/commonMain/resources/MR/fr/strings.xml
Remove mentions of "official" extensions repo. (On 18+ extensions warning)
Fixed a setting label who had the first letter in lowercase.
=> Small fix on french translation.

i18n/src/commonMain/resources/MR/tr/strings.xml
Updated some of the Turkish suffixes for the word "Mihon". They were using the suffixes of the word "Tachiyomi" which didn't work with the word "Mihon".
=> Updated Turkish suffixes

i18n/src/commonMain/resources/MR/fil/plurals.xml
Updated some Filipino Plurals to make sense grammatically.
Note:
- These are grammatical changes since some of them doesn't make any sense with the current translation.
=> Update Filipino Plurals

app/build.gradle.kts, core-metadata/build.gradle.kts, core/build.gradle.kts, data/build.gradle.kts, domain/build.gradle.kts, presentation-core/build.gradle.kts, presentation-core/src/main/java/tachiyomi/presentation/core/components/AdaptiveSheet.kt, presentation-widget/build.gradle.kts, settings.gradle.kts, source-api/build.gradle.kts, source-local/build.gradle.kts
Since the app has several modules, we can take advantage of the [gradle new feature](https://docs.gradle.org/current/userguide/declaring_dependencies.html#sec:type-safe-project-accessors). The project accessors are mapped from the project path. For example, if a project path is `:commons:utils:some:lib` then the project accessor will be `projects.commons.utils.some.lib`.
before:
```kt
dependencies {
implementation(project(":i18n"))
implementation(project(":core"))
}
```
after:
```kt
dependencies {
implementation(projects.i18n)
implementation(projects.core)
}
```
This way we don't need to relay on strings that are prone to error.
=> Adding Type-safe project accessors

app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsDataScreen.kt, presentation-core/src/main/java/tachiyomi/presentation/core/components/AdaptiveSheet.kt
This PR closes the #126
The `MultiChoiceSegmentedButtonRow` will have the Min height of its content, and the `SegmentedButton` will fill the `MultiChoiceSegmentedButtonRow` height. This combination will make both buttons have the same size and support multiple lines.
=> Fix #126: Inconsistent button height with some languages in "Data and storage"

.github/ISSUE_TEMPLATE/config.yml
The PR removes the extension-related links from the issue menu.
=> Removing extensions from config issues

app/src/main/java/eu/kanade/domain/track/interactor/RefreshTracks.kt
The problem:
When adding an enhanced tracking to an entry, the chapters wouldn't be updated as read when clicking on "tracker" to refresh read progress made on the service. The bug seems to come from [98d6ce2](https://github.com/tachiyomiorg/tachiyomi/commit/98d6ce2eaf2c1e85f4763dd37303155d1fc6690d)
Also closes #95
Possibly related to #55 , but that issue seems to be for updating progress made on Mihon, not the other way around.
=> Fix refreshing from enhanced tracker

.github/ISSUE_TEMPLATE/report_issue.yml, .github/ISSUE_TEMPLATE/request_feature.yml
Since there are no official extensions anymore, the check from the issue templates to consider opening an issue in the official repository instead in cases of issues or feature requests for for extensions, is to be removed.
=> Remove official extensions check from issue templates

app/src/main/java/eu/kanade/tachiyomi/util/CrashLogUtil.kt
Closes #223.
Checked if the file share still works as expected (it does), and it can be shared to places like Discord as previous.
=> Replace "tachiyomi" with "mihon" in crash log name

app/src/main/java/eu/kanade/presentation/reader/settings/GeneralSettingsPage.kt
"- make it behave like the one on more -> setting -> reader"
Made by @riztard but his fork is scuffed
=> Hide display cutout setting if fullscreen is off

app/src/main/java/eu/kanade/presentation/components/AdaptiveSheet.kt, presentation-core/src/main/java/tachiyomi/presentation/core/components/AdaptiveSheet.kt
All bottom sheets (dialogs) were experiencing a UI bug on API 30 and lower, where the bottom part was being cut off by the system bar. This became more noticeable when using the navigation bar. Additionally, on some devices, the dialog was adding extra padding, causing a flick in the animation. 
Another thing worth mentioning is that users on lower versions were having a different experience, as the modal was not presented in the same way as on more recent Android versions (without padding and dim background).
The proposed solution is simple: set `decorFitsSystemWindows` of the Dialog to true, so that internally the theme R.style.DialogWindowTheme is used. Additionally, extra paddings for the status bar and navigation bar were included.
I didn't understand why `decorFitsSystemWindows` was …
=> Fixing bottom sheet UI bug in non-tablet devices

app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateJob.kt
- changed extension update error file name from `tachiyomi_update_errors.txt` to `mihon_update_errors.txt`
=> change extension update error file name

gradle/compose.versions.toml
This PR closes #197 
We are using Chris Bane's compose BOM to manage the compose versions. This BOM differs from the official for using the latest non-stable versions of the libraries. This crash was caused by a bug in the compose-ui.
I could not update to the latest version because we are using several deprecated APIs that are not present in the latest version, so to update to it would not be worth the effort. Ideally, we would use the official stable version to avoid this type of crash.
Please checkout and try to reproduce the issue before merging it. I could only test it in two physical devices.
1- Go to the browser
2- Extensions tab
3- Scroll down as fast as possible
4- change tab while scrolling
5- it should not crash
https://github.com/mihonapp/mihon/assets/9647399/7bec08b0-b061-47bd …
=> Fix #197 - Scroll crashing

app/src/main/java/eu/kanade/presentation/browse/ExtensionDetailsScreen.kt
Adds some debug info about an extension to the user's clipboard when tapping the logo/name/package name area at the top of the details screen. Modeled after the debug info from the About screen.
Closes #168.
The output is formatted like this:
```
Extension name: [NAME] (lang: [LANG]; package: [PACKAGE NAME])
Extension version: [FULL SEMVER] (lib: [EXT-LIB VERSION]; version code: [EXT VERSION CODE]
NSFW: [true/false]
```
If the extension is installed, the following info is added as well:
```
Update available: [true/false]
Obsolete: [true/false]
Shared: [true/false]
Repository: [URL OF REPO]
```
So a sample output could look like
```
Extension name: MyExample (lang: en; package: eu.kanade.tachiyomi.extension.en.myexample)
Extension version: 1.4.69 (lib: 1.4; version code: 69)
NSFW: false …
```
=> Add click-to-copy extension debug info

app/src/main/java/eu/kanade/tachiyomi/extension/ExtensionManager.kt, app/src/main/java/eu/kanade/tachiyomi/ui/browse/extension/ExtensionsScreenModel.kt
closes #246
The problem mainly was that `_untrustedExtensionsFlow` wasn't updated with the new extension due to early return.
~But fixing that caused crashes due to duplicate key in LazyColumn. workaround for this was to remove duplicates for installed + untrusted extensions in `ExtensionsScreenModel`.~
~Now there is another bug, after updating and trusting an extension, it shows up two times. idk how to fix this~
=> Fix new extension install not registering in app.

.github/workflows/build_pull_request.yml, .github/workflows/build_push.yml, .github/workflows/issue_moderator.yml
As stated in this [post](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/), GitHub Actions will transition from Node 16, which has reached its EOL, to Node 20.
A couple of actions still need to be updated to Node 20, but PRs have already been opened in the relevant repositories.
- r0adkll/sign-android-release@v1 [[USE]](https://github.com/mihonapp/mihon/blob/139663acfca72b89bd9f560bf4c0c8a9155ce108/.github/workflows/build_push.yml#L50) [[PR]](https://github.com/r0adkll/sign-android-release/pull/86)
- softprops/action-gh-release@v1 [[USE]](https://github.com/mihonapp/mihon/blob/139663acfca72b89bd9f560bf4c0c8a9155ce108/.github/workflows/build_push.yml#L85) [[PR]](https://github.com/softprops/action-gh-release/pull/406)
=> Action Refactoring - Migrating Actions to Use Node 20

.github/renovate.json5
By using labels, not only does it look cleaner with some organization, but it also allows you to filter out the PRs when, for example, having a link for the user to check if something is PR'd already. Much less clutter to look at
P.S: Don't forget to actually add the label as well, preferably with proper casing, "Dependencies"
=> Add Dependencies label to Renovate Dependencies

app/src/main/java/eu/kanade/presentation/theme/TachiyomiTheme.kt, app/src/main/java/eu/kanade/tachiyomi/ui/base/delegate/ThemingDelegate.kt
Avoids triggering detekt's CyclomaticComplexMethod warning because of too many when branches, which would happen with one more theme being added in these two locations.
In TachiyomiTheme, the Monet theme is separated because it requires the current Compose context to function. The other themes do not and are delegated to a Map.
=> Minor refactor of theming when expressions

app/src/main/java/eu/kanade/domain/ui/UiPreferences.kt, app/src/main/java/eu/kanade/presentation/components/DateText.kt, app/src/main/java/eu/kanade/presentation/history/HistoryScreen.kt, app/src/main/java/eu/kanade/presentation/history/HistoryScreenModelStateProvider.kt, app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsAppearanceScreen.kt, app/src/main/java/eu/kanade/presentation/more/settings/screen/about/AboutScreen.kt, app/src/main/java/eu/kanade/presentation/more/settings/screen/debug/WorkerInfoScreen.kt, app/src/main/java/eu/kanade/presentation/track/TrackInfoDialogHome.kt, app/src/main/java/eu/kanade/presentation/track/TrackInfoDialogHomePreviewProvider.kt, app/src/main/java/eu/kanade/presentation/updates/UpdatesScreen.kt, app/src/main/java/eu/kanade/tachiyomi/ui/history/HistoryScreenModel.kt, app/src/main/java/eu/kanade/tachiyomi/ui/updates/UpdatesScreenModel.kt, app/src/main/java/eu/kanade/tachiyomi/util/lang/DateExtensions.kt
Closes #58.
Majority of work is just refactor. In a few place where a default `DateFormatter` was used, the appropriate `DateTimeFormatter` was substituted in.  As a bonus, we no longer needed many of the extension functions from `DateExtensions.kt`
=> Refactor use of Java.util.date to Java.time.*, to fix localized date issues.

app/src/main/java/eu/kanade/tachiyomi/ui/base/delegate/SecureActivityDelegate.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderActivity.kt, app/src/main/java/eu/kanade/tachiyomi/ui/webview/WebViewActivity.kt
This function is deprecated starting with API 34 "UpsideDownCake" and should be replaced with `overrideActivityTransition`.
I wasn't always sure which of `Activity.OVERRIDE_TRANSITION_OPEN` and `Activity.OVERRIDE_TRANSITION_CLOSE` to use, particularly in `SecureActivityDelegate.kt`. Otherwise, I have used the same animation parameters as were given for the deprecated method.
=> Address `overridePendingTransition` deprecation

app/src/main/java/eu/kanade/domain/track/interactor/TrackChapter.kt, app/src/main/java/eu/kanade/domain/track/service/DelayedTrackingUpdateJob.kt
DelayedTrackingUpdateJob would start spamming when it encountered an error (e.g. a tracker has an issue) and never stop. This seems to stem from a circular dependency between the Job's `doWork` and TrackChapter's `await`.
TrackChapter sets up a completely new instance of the DelayedTrackingUpdateJob if any Exception was thrown during the track update.
This causes the Job to get replaced (as per the WorkManager's set ExistingWorkPolicy).
Because of this, the guard clause at the start of doWork would never trigger, as all instances of the Job would report being the 0th try (because they were completely new instances).
This simple fix introduces a boolean `isRetry` parameter to TrackChapter's await method, which is set to `false` by default. DelayedTrackingUpdateJob however sets this …
=> Fix DelayedTrackingUpdateJob spam on update errors

app/src/main/java/eu/kanade/tachiyomi/extension/util/ExtensionLoader.kt, app/src/main/java/eu/kanade/tachiyomi/util/system/ChildFirstPathClassLoader.kt
This PR introduces a [`PathClassLoader`](https://developer.android.com/reference/dalvik/system/PathClassLoader) subclass that searches for classes in order of system, child, parent.
This is most useful when extensions use a dependency that the app may have transitively pulled in, causing conflicts and runtime errors.
Tested on ~15 other extensions, they still work fine after the change.
Closes #432
=> [ExtensionLoader] Prioritize extension classpath over app classpath

app/src/main/java/eu/kanade/domain/manga/model/Manga.kt, app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt, core-metadata/src/main/java/tachiyomi/core/metadata/comicinfo/ComicInfo.kt
I made some changes to `ComicInfo` metadata generation:
The `web field` had a schema change and can now contain multiple space separated reference website links. Therefore ComicInfo metadata will from now on include the `source URL` and all available `tracker URLs`.
For more information look at this issue https://github.com/anansi-project/comicinfo/issues/56 and this PR https://github.com/anansi-project/comicinfo/pull/57
I changed the `translator field` to use the source name if no `scanlator` name is available.
=> Made some changes to ComicInfo metadata

core/common/src/main/kotlin/tachiyomi/core/common/util/system/ImageUtil.kt
`InputStream.available()` is implementation-dependent, should never assume it will return the total number of bytes in the stream.
Fixes #479
=> Fix dual page split for local source

app/src/main/java/eu/kanade/tachiyomi/extension/installer/ShizukuInstaller.kt
Fixes bug #493.
I have successfully tested this fix by building and installing the app on my phone.
Fetch the current userid separately because shizuku always runs as the main user and would otherwise install and update for the main user
=> Fix shizuku being buggy for multi user setups

app/src/main/java/eu/kanade/tachiyomi/data/saver/ImageSaver.kt
While most Android skins are seemingly able to handle the millisecond format, the documentation technically specifies seconds. This seems to be causing issues on Samsung devices using the Samsung Gallery app, which renders the millisecond timestamps as if they were second ones, causing the dates to be set at some point in the year 56189.
This change should fix that issue on Samsung devices and have no real impact on the rest.
Credit to @sirlag for figuring out the core issue :)
=> Switch to seconds for DATE_MODIFIED of saved pages

app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonLayoutManager.kt
Covers the case when image height > screen height.
=> Fix webtoon last visible item position calculation

app/src/main/java/eu/kanade/presentation/manga/DuplicateMangaDialog.kt, app/src/main/java/eu/kanade/tachiyomi/ui/browse/migration/search/SourceSearchScreen.kt, app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/browse/BrowseSourceScreen.kt, app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/browse/BrowseSourceScreenModel.kt, app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaScreen.kt, app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaScreenModel.kt, i18n/src/commonMain/resources/MR/base/strings.xml
Added the option to migrate a manga to a different source directly from the Duplicate found dialog. Because of the additional options, the dialog has been reworked into a sheet.
Behavior works on both locations for the Duplicate dialog to appear (Manga page and Source Browser). 
There is a small graphical anomaly when migrating on the Manga screen where the dialog persists on screen very briefly.
Closes #489 
| Phone UI | Tablet UI |
| ------- | ------ |
| ![image](https://github.com/mihonapp/mihon/assets/1882979/66502a22-f4d1-4317-974d-ecc72e675c8d?width=540&height=1200) | ![image](https://github.com/mihonapp/mihon/assets/1882979/498f8afc-cdc7-4f45-ab60-30355eaedac3) |
=> Rework Duplicate Dialog and Allow Migration

domain/src/main/java/mihon/domain/extensionrepo/service/ExtensionRepoDto.kt, domain/src/main/java/mihon/domain/extensionrepo/service/ExtensionRepoService.kt
Slightly refactored the `ExtensionRepoService` so it uses DTO data classes with `parseAs` to avoid parsing the JSON response by hand.
The default Json instance Injekt provides here has `ignoreUnknownKeys` enabled, so the `ExtensionRepoMetaDto` only specifies the meta key of the response content.
The extension function `toExtensionRepo` allows for mapping the new DTO to the `domain`'s `ExtensionRepo` data class.
=> Refactor the ExtensionRepoService to use DTOs

app/src/main/java/eu/kanade/presentation/more/settings/screen/browse/components/ExtensionReposContent.kt
This applies to both the item being shown in the screen as well as the “copy to clipboard” button. Before, copying a repo URL would return “The Repo Name/index.json.min”. This PR fixes that.
Edit: I misunderstood the original intent, now the whole ExtensionRepo is passed to the item display, which uses the name for displaying and the baseUrl for copying the URL.
=> Fix repo name used for URL instead of baseUrl

app/proguard-rules.pro
Should fix type resolver issues in new mihon.** namespace files
=> Add ProGuard rule to keep mihon namespace classes

data/src/main/java/tachiyomi/data/manga/MangaRepositoryImpl.kt, data/src/main/sqldelight/tachiyomi/data/mangas.sq
Super quick fix for @Soitora to ensure that manga with update dates in the future don't display in the upcoming page.
=> Moves upcoming requirement from existence to current day or later.

.github/renovate.json5, gradle/compose.versions.toml, presentation-core/src/main/java/tachiyomi/presentation/core/components/AdaptiveSheet.kt
* This PR is not to update to the latest Compose BOM due to regressions found in Compose Foundation `1.7.0-alpha06`.
* Chris Banes' Compose BOM is always unstable so renovate won't update it.
* `org.jetbrains.kotlin` prefix is too permissive and will match kotlinx dependencies.
* `AnchoredDraggable`'s `currentValue` has its behaviour changed in Compose Foundation [`1.7.0-alpha05`](https://developer.android.com/jetpack/androidx/releases/compose-foundation#1.7.0-alpha05).
* Compose Material 3 [`1.3.0-alpha02`](https://developer.android.com/jetpack/androidx/releases/compose-material3#1.3.0-alpha02) fixed the RTL issue with `Slider`, and [`1.3.0-alpha03`](https://developer.android.com/jetpack/androidx/releases/compose-material3#1.3.0-alpha03) updated `Slider` specs.
Fixes #651
=> Update compose bom and fix renovate config for it

.github/workflows/issue_moderator.yml
This rule is intended to automatically close issues that report problems with linking MAL that would be solved with the standard solution of updating & changing the default UA.
The RegEx might be too general, but there isn't any neat pattern in the previously filed issues.
Also not sure if the listed version should stay as "0.16.4 or newer" or if it should be changed to the latest version when cutting a release.
The response would look like this:
For issues with linking MyAnimeList, please follow these steps:
1. Update Mihon to version 0.16.4 or newer
2. Change your default User-Agent (`More → Settings → Advanced → Default user agent string`)
3. Close and restart Mihon
4. Attempt to link MyAnimeList again
If you had MyAnimeList linked before, try to unlink it first before trying these …
=> Add MyAnimeList issue autoclose

app/src/main/java/eu/kanade/tachiyomi/data/coil/TachiyomiImageDecoder.kt, app/src/main/java/eu/kanade/tachiyomi/data/coil/Utils.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderActivity.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/ReaderPageImageView.kt
Follow-up of #691
This PR switchs to Coil pipeline for image decode in webtoon mode, images are now always loaded as a whole instead of tiles.
This significantly improves performance with extremely long (> 16k) images from testing.
Here is a benchmark build if anyone wants to test.
https://github.com/FooIbar/mihon/actions/runs/8765855174
=> Use Coil pipeline instead of SSIV for image decode

app/src/main/java/eu/kanade/presentation/crash/CrashScreen.kt, app/src/main/java/eu/kanade/tachiyomi/util/CrashLogUtil.kt
So the user won't need to screenshot the crash screen.
=> Log exceptions in dumped crash logs

app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadProvider.kt, app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt, gradle/libs.versions.toml, source-local/src/androidMain/kotlin/tachiyomi/source/local/LocalSource.kt, source-local/src/androidMain/kotlin/tachiyomi/source/local/io/LocalSourceFileSystem.kt
Please see https://github.com/mihonapp/mihon/issues/705 for a technical discussion of the issue being solved here. This is a follow-on to https://github.com/tachiyomiorg/UniFile/pull/2, which uses the newly optimized version of UniFile and adjusts `findFile` callsites to adapt to the removed `ignoreCase` argument.
As per standard development procedure, this branch can be compiled using `./gradlew assembleDevDebug` and installed for testing. I have temporarily configured `libs.versions.toml` to pull the specific commit from my UniFile branch via [JitPack](https://jitpack.io/), but this will of course be updated to point to the official repository master branch once the other pull request is merged (and/or the repository, which still lives under the legacy `tachiyomiorg` organization, is …
=> Massively improve findFile performance

app/src/main/java/eu/kanade/presentation/more/settings/screen/browse/components/ExtensionReposDialogs.kt
Hi,
This PR changes the URL input in the add extension repo dialog to be of URI type. This disables auto correct (so e.g. githubusercontent wont be autocorrected to GitHub user content) and also adds characters such as '/' to the front page of the keyboard.
=> Change keyboard type in extension repo dialog

app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonRecyclerView.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonViewer.kt
Fixes https://git.mihon.tech/tachiyomi/tachiyomi/issues/4875
=> Fix tap control area shifting after zooming out

app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsDataScreen.kt, i18n/src/commonMain/resources/MR/base/strings.xml
Re-opened #645 due to me doing a wrong `rebase`.
Fixes #395.
I had the same issue with a news app I've programmed.
These devices run a custom Android OS that does not correctly implement the SAF. The `FileProvider` that is responsible for handling the `OPEN_DOCUMENT_TREE` `Intent` probably does not set the `PERSISTABLE_URI` flag. Thus, the call to `takePersistableUriPermission` fails with a `SecurityException`; no valid tickets are available.
This workaround gets the user passed the onboarding screen. I have tested this using manga I bought online and the default file path of `/Mihon`. 
I want to note that, after selecting the file path during the onboarding experience, the app would still tell me `No folder has been selected`, but the next button was clickable. I think the issue is that …
=> fix: storage permission request for non-conforming devices

app/src/test/java/mihon/core/migration/MigratorTest.kt
Causing error: io.mockk.MockKException: was not can only be called on a mocked object
=> Fix MigratorTest after update to io.mockk v1.13.11

build.gradle.kts, settings.gradle.kts
This reverts commit f3226fb278cab87422255e04e647c50095b61529.
Somehow it was still using the bundled R8, see https://github.com/FooIbar/mihon/actions/runs/9534770159 and https://github.com/FooIbar/mihon/actions/runs/9534906033
Closes #915
=> Fix R8 version configuration not working

gradle/compose.versions.toml, source-api/build.gradle.kts, source-api/src/commonMain/kotlin/eu/kanade/tachiyomi/source/model/FilterList.kt
In strong skipping mode, Composables with unstable parameters become skippable and unstable parameters are compared using instance equality (`===`).
Since all parameters are unchanged, [`SourceFilterDialog`](https://github.com/mihonapp/mihon/blob/b37357f9097730edb1d72f1297461e580286856c/app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/browse/SourceFilterDialog.kt#L34) will be skipped.
This PR marks `FilterList` as stable to use object equality ([`Object.equals()`](https://github.com/mihonapp/mihon/blob/b37357f9097730edb1d72f1297461e580286856c/source-api/src/commonMain/kotlin/eu/kanade/tachiyomi/source/model/FilterList.kt#L8)) to compare so they will never be equal.
There are probably some similar bugs introduced by strong skipping mode unspotted.
Fixes #893
=> Fix unexpected skips in strong skipping mode

app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsReaderScreen.kt, app/src/main/java/eu/kanade/presentation/reader/DisplayRefreshHost.kt, app/src/main/java/eu/kanade/presentation/reader/settings/GeneralSettingsPage.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/setting/ReaderPreferences.kt, i18n/src/commonMain/moko-resources/base/plurals.xml, i18n/src/commonMain/moko-resources/base/strings.xml
Adds some configuration options for the e-ink page flash to better support a variety of devices. 
Added Flash duration options - 100-1500ms
Added Flash style options - Black, White, White/Black
Added Flash spacing options - 1 - 10 pages
The current page flash system really is a hack over the reader (adding a colored rectangle over the reader for the duration of the flash) hooked into every page. Trying to use this hook to enable and disable the invert filter had low success, particularly because it only triggers after the page change animation has already started to play. Attempt to add a proper invert or inline screen clear will probably require a refactor for on-exit hooks that can delay a transition, but that seemed beyond the scope of getting this more usable for our e-ink users.
| …
=> Added configuration options to e-ink page flashes

buildSrc/settings.gradle.kts
`Project accessors enabled, but root project name not explicitly set for 'buildSrc'. Checking out the project in different folders will impact the generated code and implicitly the buildscript classpath, breaking caching.`
=> buildSrc: Fix strange warning in ci build

core/common/src/main/kotlin/mihon/core/common/archive/ArchiveInputStream.kt
In case something try to close it twice or library change their behaviour to auto-close the InputStream (e.g. [Jsoup](https://github.com/jhy/jsoup/blob/1f1f72d1e89821c630dcfc35e1a0a7f653cc877b/src/main/java/org/jsoup/helper/DataUtil.java#L233)).
Closes GH-966
=> Add safeguard to prevent ArchiveInputStream from being closed twice

gradle/libs.versions.toml
Enables >8-bit AVIF decoding. (for real this time)
Closes https://github.com/mihonapp/mihon/issues/946
=> Update image-decoder revision

app/src/main/java/eu/kanade/presentation/manga/components/MangaDialogs.kt, i18n/src/commonMain/moko-resources/base/strings.xml
#975 
| Image 1 | Image 2 |
| ![Screenshot_20240702_193622_TachiyomiSY](https://github.com/mihonapp/mihon/assets/40583749/69684e8a-d635-47fb-9919-a6900d5e5f5c)| ![Screenshot_20240702_230633_Mihon](https://github.com/mihonapp/mihon/assets/40583749/48abd55e-1572-49cb-8818-ed1ce18abcd3)
|
=> Smart Update Dialog Tweak

app/src/main/java/eu/kanade/presentation/library/LibrarySettingsDialog.kt, app/src/main/java/eu/kanade/presentation/more/settings/PreferenceItem.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/BaseTracker.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/Tracker.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/TrackerManager.kt, app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryScreenModel.kt, app/src/main/java/eu/kanade/tachiyomi/ui/library/LibrarySettingsScreenModel.kt, app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaScreen.kt, app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaScreenModel.kt, app/src/main/java/eu/kanade/tachiyomi/ui/manga/track/TrackInfoDialog.kt, app/src/main/java/eu/kanade/tachiyomi/ui/stats/StatsScreenModel.kt, app/src/main/java/eu/kanade/test/DummyTracker.kt
=> Observe tracker login state instead of fetching once

app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadManager.kt, app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt, app/src/main/java/eu/kanade/tachiyomi/data/saver/ImageSaver.kt, core/common/src/main/kotlin/tachiyomi/core/common/util/system/ImageUtil.kt
Avoid using platform mime type map to get extensions as it may not have all mime types we support.
This also fixes the performance issue of reading jxl archives, wrong file extensions and can't open downloaded files.
Fixes #566
=> Fix some issues when reading/saving images

app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsLibraryScreen.kt, gradle/libs.versions.toml
Category Names that cause crashes Fixes #1029 
- Anything that ends in %
- %c
- %d
- %e
- %f
- %g
- %o
- %t
- %x
- `%` displays `crashes`
- `%%` displays `%`
- `%%%` displays `crashes`
- `%%%%` displays `%%`
- so on and so forth xD
Category Names that cause weird behavior
- %b - Displays `True`
- %h - Displays `4e3`
- %n - Adds a newline
Category Names that work
- %s
Crash occurs when category with said name is set as default category.
```diff
Preference.PreferenceItem.ListPreference(
pref = libraryPreferences.defaultCategory(),
title = stringResource(MR.strings.default_category),
-         subtitle = selectedCategory?.visualName ?: stringResource(MR.strings.default_category_summary),
+         subtitle = selectedCategory?.visualName?.replace("%", "%%") ?: …
```
=> Format Category String on Subtitle Display

app/src/main/java/eu/kanade/presentation/browse/ExtensionsScreen.kt, app/src/main/java/eu/kanade/presentation/browse/SourcesFilterScreen.kt, app/src/main/java/eu/kanade/presentation/history/HistoryScreen.kt, app/src/main/java/eu/kanade/presentation/updates/UpdatesUiItem.kt, app/src/main/java/eu/kanade/presentation/util/FastScrollAnimateItem.kt
Due to update compose-bom and migration from `animateItemPlacement` to `animateItem` which by default includes fade-in/fade-out spec, while doing a fast scrolling, items look like disappeared.
=> Don't use fade-in/fade-out with `FastScrollLazyColumn`.
=> Fix disappearance items when fast scrolling

app/src/main/java/eu/kanade/presentation/reader/ReaderPageActionsDialog.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderActivity.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderViewModel.kt
Uses Android's ClipboardManager to copy an Panel to the clipboard.
=> Adds Option to Copy Panel to Clipboard

app/src/main/java/eu/kanade/tachiyomi/data/backup/BackupDecoder.kt, i18n/src/commonMain/moko-resources/base/strings.xml
Older versions of Tachiyomi support backing up and restoring from JSON files. If a user tries to restore from such a backup they should be nudged in correct direction. Currently the error message is very cryptic and leads to a support burden:
> kotlinx.serialization.protobuf.internal.ProtobufDecodingException: Unsupported start group or end group wire type: 3
Users are likely to expect old JSON backups to still be usable in Mihon, unless told directly. With the proposed change there is a de minimis maintenance/performance burden as it hooks into the existing gzip signature check. The new error message:
> java.lang.Exception: JSON backup not supported
If the user picks a JSON file that is not a backup file from Tachiyomi the error message will falsely imply that the file is a valid …
=> Improve error message if restoring from JSON file

app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonLayoutManager.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonViewer.kt
And increase recycler item view cache size.
This should fix the issue in https://github.com/mihonapp/mihon/issues/779#issuecomment-2253459492.
=> Match extra layout space with scroll distance

README.md, app/src/main/java/eu/kanade/tachiyomi/data/track/kitsu/KitsuApi.kt
cf. https://github.com/hummingbird-me/kitsu-server/commit/244fdccca9754d8579c049e738832843001b33b1
These changes work because I've already done this same change to my fork which works.
Closes #1104.
=> Change Kitsu to kitsu.app domain

app/src/main/java/eu/kanade/tachiyomi/data/track/myanimelist/MyAnimeListApi.kt
The previous approach would always throw an Exception because `SimpleDateFormat.format()` expects the input to be of type `Date` or `Number`, not `String`.
=> Fix MAL search results not showing start dates

app/src/main/java/eu/kanade/presentation/track/TrackInfoDialogHome.kt, app/src/main/java/eu/kanade/presentation/track/TrackInfoDialogHomePreviewProvider.kt, app/src/main/java/eu/kanade/presentation/track/components/TrackLogoIcon.kt, app/src/main/java/eu/kanade/tachiyomi/ui/manga/track/TrackInfoDialog.kt, i18n/src/commonMain/moko-resources/base/strings.xml
resolves #1087. 
When the icon for a tracker is held down, the tracker URL is copied to the clipboard, if it exists. 
From @BrutuZ's comment, I have also added it to the menu:
=> Add Copy Tracker URL on icon long press

app/src/main/java/eu/kanade/presentation/reader/appbars/ReaderAppBars.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderActivity.kt
Resolves #1077 by adding an "open in browser" button to the menu
Clicking it opens the chapter in the default browser.
=> Add an "open in browser" button to reader menu

app/src/main/java/mihon/core/migration/migrations/SetupBackupCreateMigration.kt, app/src/main/java/mihon/core/migration/migrations/SetupLibraryUpdateMigration.kt
Both `SetupBackupCreateMigration` and `SetupLibraryUpdateMigration` were trying to get the `App` class from Injekt which is never provided via the `AppModule`. This caused them to always return `false` and never actually setting up the jobs,
Using `Application` instead works since the `workManager` property used by the respective `setupTask` functions is an extension property on `Context`.
=> Fix some migrations never running

app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonViewer.kt
Note for forks: Increasing cache size may cause OOM on API < 26, better to make it API 26+ only.
=> Add comment about RecyclerView cache size

CHANGELOG.md, app/src/main/java/eu/kanade/tachiyomi/extension/api/ExtensionUpdateNotifier.kt
Removes the extension names from the notification when hide notification content is turned on.
Fixes #1022 
| Before | After |
| ![Before](https://github.com/user-attachments/assets/995789f4-63d2-48ed-9878-477fa996b7d3) | ![After](https://github.com/user-attachments/assets/3a3f85a0-2476-491e-81e8-da5c93bc3a95) |
=> Respect privacy settings in extension update notification

app/src/main/java/eu/kanade/tachiyomi/data/download/DownloadNotifier.kt, app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt, app/src/main/java/eu/kanade/tachiyomi/data/notification/NotificationReceiver.kt
Adds a "Show entry" action to the following download notifications, allowing user to restart the download or view the entry:
- Normal: When showing download progress 
- Errors:
- insufficient space
- generic chapter error
- generic image error
- Warnings: None
Provides a meaningful way to address the root cause, and resolve #1129
=> Add "show entry" action to download notifications 

domain/src/main/java/tachiyomi/domain/download/service/DownloadPreferences.kt
Set to `true` to make 'Split tall images" enabled by default
=> Enable 'Split Tall Images' by default

app/src/main/java/eu/kanade/domain/track/interactor/TrackChapter.kt, app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaScreenModel.kt, i18n/src/commonMain/moko-resources/base/strings.xml
Shows a snack bar to update trackers when you mark chapters as read.
Closes #619 
More Context : https://git.mihon.tech/tachiyomi/tachiyomi/issues/389#issuecomment-28053
=> Option to update trackers when chapter marked as read

app/src/main/java/eu/kanade/tachiyomi/data/track/kitsu/dto/KitsuListSearch.kt
The [Kitsu API docs](https://kitsu.docs.apiary.io/#reference/user-libraries/library-entries) (and the responses) type `ratingTwenty` as a "number" (Int in Kotlin, it's divided by 2 for a .5 step scale 0-10). It's nullable because an entry without a user rating returns `null` in that field.
This caused crashes when a user would attempt to add Kitsu as a tracker for an entry in Mihon while already having the entry tracked in Kitsu through some other means AND having assigned the entry a score on Kitsu.
=> Fix Kitsu `ratingTwenty` being typed as String

app/src/main/java/eu/kanade/presentation/webview/WebViewScreenContent.kt
Webview can't handle `intent://` urls, returning `true` cancels the request.
Issue example: https://github.com/keiyoushi/extensions-source/issues/3810
=> Ignore "intent://" urls on webview

domain/src/main/java/tachiyomi/domain/manga/interactor/FetchInterval.kt
it was using the negative value of custom fetchInterval to calculate nextUpdate and causing a nextUpdate date in the past
=> Fix: wrong calculation of nextUpdate when setting custom fetchInterval

app/src/main/java/eu/kanade/tachiyomi/data/track/kitsu/dto/KitsuListSearch.kt
This time, the Kitsu API docs are silent on whether this field (or any other field) can be null/undefined/etc, but it can happen and caused an error during search and update. This change just ensures the attribute is nullable and is set to an empty String when it is null.
I hope this will be the last of the Kitsu fixes but honestly, I don't know anymore.
=> Fix Kitsu `synopsis` nullability

i18n/src/commonMain/moko-resources/base/strings.xml
`Extension Repos` -> `Extension repos`
=> Fix Casing for Extention Repos String

app/src/main/java/eu/kanade/domain/track/interactor/SyncChapterProgressWithTrack.kt
This PR is related to #1298.
When adding an item to the library, with the #1298 fix, the track's last_read_chapter value set by `SyncChapterProgressWithTrack` is always set to the local last read chapter.
This fix uses the max between the local and remote last read chapter to set its new value.
=> Retain remote last chapter read if it's higher than the local one for EnhancedTracker

app/src/dev/java/mihon/core/firebase/Firebase.kt, app/src/main/java/eu/kanade/presentation/more/onboarding/PermissionStep.kt, app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsSecurityScreen.kt, app/src/main/java/eu/kanade/tachiyomi/App.kt, app/src/main/java/eu/kanade/tachiyomi/di/PreferenceModule.kt, app/src/standard/AndroidManifest.xml, app/src/standard/java/mihon/core/firebase/Firebase.kt, core/common/src/main/kotlin/eu/kanade/tachiyomi/core/security/PrivacyPreferences.kt, core/common/src/main/kotlin/eu/kanade/tachiyomi/core/security/SecurityPreferences.kt, i18n/src/commonMain/moko-resources/base/strings.xml
Resolves #1187
Adds options to both Onboarding and the Security and Privacy Screen to toggle Analytics and Crashlytics
| Before | After | 
|---|---|
| ![image](https://github.com/user-attachments/assets/cbf6c952-7605-455d-bde8-938c827d8baa) | ![image](https://github.com/user-attachments/assets/b17c3a4e-20a1-41a6-80f1-26a8f9dff6a5) | 
| ![image](https://github.com/user-attachments/assets/e2ed5089-2b43-41de-bb59-67c56fdc8d5c) | ![image0](https://github.com/user-attachments/assets/66677a8b-1542-4fd6-91dc-e5b92b621973) |
=> Add option to opt out of Analytics and Crashlytics

app/src/main/java/eu/kanade/core/util/CollectionUtils.kt, app/src/main/java/mihon/feature/upcoming/UpcomingScreenContent.kt, app/src/main/java/mihon/feature/upcoming/UpcomingScreenModel.kt, app/src/main/java/mihon/feature/upcoming/UpcomingUIModel.kt
Fixes #1227 
| ![Screenshot_20240919_105658_Mihon](https://github.com/user-attachments/assets/bfc5a916-e97b-4861-b0e5-26b447f742ec) | ![Screenshot_20240919_105752_Mihon](https://github.com/user-attachments/assets/1fdc5b90-82b9-4ad5-bbdd-c0dfbbf1ccf2) |
|---|---|
=> Add Quantity Badge to Upcoming Screen

app/src/main/java/eu/kanade/presentation/library/LibrarySettingsDialog.kt, app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryScreenModel.kt, domain/src/main/java/tachiyomi/domain/category/interactor/SetSortModeForCategory.kt, domain/src/main/java/tachiyomi/domain/library/model/LibrarySortMode.kt, domain/src/main/java/tachiyomi/domain/library/service/LibraryPreferences.kt, domain/src/test/java/tachiyomi/domain/library/model/LibraryFlagsTest.kt, i18n/src/commonMain/moko-resources/base/strings.xml, presentation-core/src/main/java/tachiyomi/presentation/core/components/SettingsItems.kt
Replacing https://github.com/mihonapp/mihon/pull/1315 because I was using my main branch like a goon
Problem:
If you have a large bulk from a source that uses something that interferes with alphabetical tagging - e.g. a comic source that leads its releases with the year ([2019], ex), the sort options will group every title like that together when, personally, I've found I sometimes want to view my library in a way that scatters them more evenly. Sometimes I don't want to view my stuff chronologically.
Also I just like random sort.
Behavior:
Using a single random seed for all categories. The seed for all categories using random sort will change any time a section switches to random or taps on the randomization again. I believe this should line up with expected behavior and that users don't …
=> Added random library sort

app/src/main/java/eu/kanade/presentation/browse/ExtensionsScreen.kt, app/src/main/java/eu/kanade/tachiyomi/ui/browse/extension/ExtensionsTab.kt, i18n/src/commonMain/moko-resources/base/strings.xml
Adds a confirmation dialog on long tap of an extension installed with the Private Installer as it lacks a system confirmation.
https://git.mihon.tech/tachiyomi/tachiyomi/issues/9864
=> Confirmation dialog when removing privately installed extensions

app/src/main/java/eu/kanade/domain/track/interactor/AddTracks.kt
This PR is an attempt to fix the issue #306.
Tracking used to be enabled by default when adding an item to the library, which is not the case anymore.
This fix tries to bind with all logged In enhanced trackers upon adding an item to the library.
~~I think there still is an issue with the track being saved with a `last_read_chapter` value of 0.0, but the problem seems to lie in the `SyncChapterProgressWithTrack` and is not introduced by this fix.~~
=> Fix EnhancedTracker not auto binding when adding manga to library

presentation-core/src/main/java/tachiyomi/presentation/core/components/SettingsItems.kt
Small error with how sliders are implemented that i noticed when trying to implement other changes. steps should be 1 less than the amount of steps you want if you are defining min and max, because steps takes in the amount of inner steps excluding the lowest and highest. as it is now if the slider passes the middle step, its starts skipping by 2 whenever decrementing.
(added a dummy slider so its easier to see, not in the code pushed)
example of slider now
https://github.com/user-attachments/assets/8d4231c0-411b-427f-a134-7a24278c1d8a
example of slider fixed
(https://github.com/user-attachments/assets/6e1a5ca8-c063-4c3e-b187-0f9972c77bb9)
=> Fix off by one error in SliderItem

app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsDownloadScreen.kt, app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsLibraryScreen.kt
`SettingsLibraryScreen` & `SettingsDownloadScreen` is using runBlocking to load categories list which will cause a bit lag while waiting for data from DB, especially for users with large library.
=> avoid using runBlocking to load categories in Settings

presentation-widget/build.gradle.kts
Not sure which changes caused this but recently my Android Studio always got this error:
`ERROR: AAPT: tachiyomi.presentation.widget.test.presentation-widget-mergeDebugAndroidTestResources-70:/values-v31/values-v31.xml:3: error: resource color/m3_sys_color_dynamic_light_surface (aka tachiyomi.presentation.widget.test:color/m3_sys_color_dynamic_light_surface) not found.`
Although CI build still works fine on Github Action.
=> add missing material lib to presentation-widget

CHANGELOG.md, app/src/main/java/eu/kanade/tachiyomi/data/track/bangumi/BangumiApi.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/bangumi/dto/BGMSearch.kt
In short:
- fetch & show actual summary
- fallback to "name" if "name_cn" is empty
- request larger responseGroup to get & display the summary & rating
- add type filter query param to make Bangumi filter, not us
Previously, we only displayed the "name" in the summary area and used "name_cn" as the entry name. However, "name_cn" (Chinese name) can be an empty string at times, resulting in an awkward looking search result list where some, many, or even all the results have no title displayed and only show the "name" (Japanese name) in the summary area. This has been solved by using "name" as a fallback value should "name_cn" be empty.
By using the "responseGroup=large" query parameter, we can request the required data we need to display the actual summary for an entry and the entry's …
=> Various improvements to Bangumi search

app/build.gradle.kts, app/src/main/java/eu/kanade/tachiyomi/data/saver/ImageSaver.kt, buildSrc/src/main/kotlin/mihon/buildlogic/ProjectExtensions.kt, core/common/build.gradle.kts, core/common/src/main/kotlin/eu/kanade/tachiyomi/util/system/WebViewUtil.kt, data/build.gradle.kts, domain/build.gradle.kts, i18n/build.gradle.kts, i18n/src/commonMain/moko-resources/base/strings.xml, presentation-core/build.gradle.kts, presentation-core/src/main/java/tachiyomi/presentation/core/components/SettingsItems.kt, source-api/build.gradle.kts, source-local/build.gradle.kts
=> Address some build warnings and cleanup

app/src/main/java/eu/kanade/tachiyomi/util/system/ContextExtensions.kt
1. Set Reader's background color mode to *Auto*
2. System is in Light mode, App theme is in Dark mode; OR System is in Light mode, App theme is in Dark mode
=> fix: reader's transition dark/light theme was wrong in auto mode

app/src/main/java/eu/kanade/tachiyomi/data/notification/Notifications.kt, app/src/main/java/eu/kanade/tachiyomi/data/updater/AppUpdateNotifier.kt
1. Try downloading the app update on a slow network - Or purposely decrease `network.client.callTimeout` to just 1-3 seconds.
2. Wait for the timeout exception to occur (could be any other exception that could be manipulated to occur)
- The `Download Error` notification should be shown after the `Downloading` notification hides.
- The `Downloading` notification hides and there are no more notification.
- `AppUpdateDownloadJob` foreground is set tied to `Notifications.ID_APP_UPDATER`
- The `Download Error` notification also use `Notifications.ID_APP_UPDATER` - debug shows that it is actually called to show
- But when Job is done (i.e. download stoped for any reason), the whole `Notifications.ID_APP_UPDATER` is closed and hence clearing the `Download Error` notification.
=> fix: app update error notification always disappeared

core/common/src/main/kotlin/eu/kanade/tachiyomi/util/system/DeviceUtil.kt
Closes #1348.
Specifically adds com.hihonor.android.internal.app to the list of invalid browsers. It's very similar to the existing entry for Huawei, so it stands to reason it is the same/similar problem as with Huawei's internal app.
=> Add weird Honor app to list of invalid browsers

CHANGELOG.md, app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsAdvancedScreen.kt, core/common/src/main/kotlin/tachiyomi/core/common/util/system/ImageUtil.kt
Declares all listed devices as unable to use hardware bitmaps and hides the Hardware Bitmap Threshold setting on all such devices.
Might fix #1541.
=> Include Coil's broken hardware bitmap device list

CHANGELOG.md, app/src/main/java/eu/kanade/tachiyomi/data/track/myanimelist/MyAnimeListApi.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/myanimelist/dto/MALManga.kt
If a manga doesn't have a cover, MAL doesn't provide the `main_picture` element in the API response at all.
The long-unwanted sequel to the DTO migration fuckup saga. Please let this be the last one.
=> Fix MAL manga cover nullability

CHANGELOG.md, app/src/main/java/eu/kanade/tachiyomi/util/CrashLogUtil.kt
This should help distinguish log entries that happened recently and may be related to crashes from older entries that occurred before now.
This affects the debug info copied from the About screen as well as crash logs (both dumped manually as well as created on crash).
Example output taken from the About screen in my emulator:
```
App version: 0.17.1-7063 (dev, 82fd89cee, 9, 2025-01-27T12:29:30Z)
Android version: 14 (SDK 34; build UE1A.230829.036.A4)
Device brand: google
Device manufacturer: Google
Device name: emu64xa (sdk_gphone64_x86_64)
Device model: sdk_gphone64_x86_64
WebView: Android System WebView 130.0.6723.58
Current time: 2025-01-27T13:37:15.371075+01:00
```
<details>
<summary>Example output taken from a manual crash log dump</summary>
```
App version: 0.17.1-7063 (dev, …
```
=> Add zoned date & time to debug info & logs

CHANGELOG.md, app/src/main/java/eu/kanade/tachiyomi/data/track/myanimelist/dto/MALOAuth.kt
Similar to the situation with Bangumi, the missing annotation means [kotlinx.serialization would _provide_ the default value upon instantiation but not serialise it to disk](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/basic-serialization.md#defaults-are-not-encoded-by-default). This means the isExpired() calculation would effectively rarely/never do its job correctly, leading to Mihon sending expired tokens to MAL and causing problems for everyone involved.
Overall, this change _could_ (should) lead to a drastic reduction in MAL requests failing, leading to users having to relink their MAL accounts.
Also switched createdAt to be in seconds instead of milliseconds as all other trackers use seconds for timestamps (except for AniList, which uses milliseconds but doesn't …
=> Add missing @EncodeDefault annotation to MALOAuth

CHANGELOG.md, core/common/src/main/kotlin/eu/kanade/tachiyomi/util/system/DeviceUtil.kt
`com.transsion.resolver` being picked by the system as a suitable browser caused a Mihon user with an Infinix device to be unable to open any links in browsers, including tracker login and opening a WebView page in a real browser.
Filtering this resolver via our list of invalid browsers enabled the system to suggest their Chrome browser instead, making the affected features work again as expected.
=> Add Infinix system app to list of invalid browsers

CHANGELOG.md, source-local/src/androidMain/kotlin/tachiyomi/source/local/LocalSource.kt
Local Source properly ignores hidden folders (dot prefix) within the `local` folder in the _MangasPage_, however that was not the case for subfolders (chapters) in the entry, leading to undesired results such as:
```tree
/storage/emulated/0/Mihon/local/Demo Entry/
├── .metadata
│   └── chapters_details.zip
├── Ch. 01.cbz
└── Ch. 02.cbz
```
| Before | After |
=> Ignore hidden files/folders for Local Source chapters

CHANGELOG.md, app/src/main/java/eu/kanade/domain/manga/model/Manga.kt, app/src/main/java/eu/kanade/presentation/manga/ChapterSettingsDialog.kt
=> Apply "Downloaded only" filter to non library entries as well

CHANGELOG.md, app/build.gradle.kts, app/src/main/java/eu/kanade/domain/DomainModule.kt, app/src/main/java/mihon/core/migration/migrations/CategoryPreferencesCleanupMigration.kt, app/src/main/java/mihon/core/migration/migrations/Migrations.kt, app/src/main/java/mihon/core/migration/migrations/RemoveNonReferredCategoryPreferencesMigration.kt, domain/src/main/java/tachiyomi/domain/category/interactor/DeleteCategory.kt
When a category is deleted, preferences which are referencing to that category should also be clear to avoid null/incorrect settings
=> remove reference to Preferences of deleting category

CHANGELOG.md, app/src/main/java/eu/kanade/tachiyomi/data/track/bangumi/Bangumi.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/bangumi/BangumiApi.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/bangumi/BangumiInterceptor.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/bangumi/BangumiUtils.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/bangumi/dto/BGMCollectionResponse.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/bangumi/dto/BGMSearch.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/bangumi/dto/BGMUser.kt
This comes with many benefits:
- Starting dates are now available and shown to users
- Lays groundwork to add private tracking for Bangumi, e.g. in #1736
- Mihon makes approximately 2-4 times fewer calls to Bangumi's API
- Simplified interceptor for the access token addition
- v0 does not allow access tokens in the query string
- There is [actively maintained documentation](https://bangumi.github.io/api/) for it
Also shrunk the DTOs for Bangumi by removing attributes we have no use for either now or in the foreseeable future. Volume data remains in case Mihon wants to ever support volumes. But attributes such as user avatars, nicknames, data relating to Bangumi's tag & meta-tag systems, etc. have been removed or just not added to the DTOs.
If the volume data attributes should also be …
=> Migrate to Bangumi's newer v0 API

app/src/main/java/eu/kanade/tachiyomi/data/track/bangumi/Bangumi.kt
Most if not all other trackers do this too. Technically this causes some request duplication (since things like the BaseTracker's setRemoteLastChapterRead fire anyway due to the tracker sheet being open). But considering the reduced number of requests in other places, I think this is still acceptable.
Forgot to say why:
This makes sure that we update Bangumi with our new local data where applicable (like private tracking state).
This change will allow #1736 to proceed, hopefully.
What have we learned from this? Actually think about code. Also, don't hide request stuff in base classes but that's not actionable here.
=> Add back explicit update(track) call to Bangumi

app/src/main/java/eu/kanade/tachiyomi/data/track/bangumi/Bangumi.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/bangumi/BangumiApi.kt
Caused by #1748.
Two different issues actually.
Firstly, the getUsername API call uses the authClient, which uses the BangumiInterceptor to get the current OAuth data and attach the Authorization header. However, on login, #1748 did not try to set the new auth details until after attempting to call getUsername. This would cause Mihon to think the user was not authenticated with Bangumi and cancel the process.
This is fixed by having Mihon store the OAuth credentials in the interceptor first before attempting to call getUsername.
The second issue is a simple trailing dollar sign in the API URL for the getUsername method. This was removed.
This wasn't caught because I added the username fetching later after having already linked Bangumi in the emulator. I didn't think to relink it from …
=> Fix Bangumi linking regression

CHANGELOG.md, app/src/main/java/eu/kanade/presentation/webview/WebViewScreenContent.kt, app/src/main/java/eu/kanade/tachiyomi/App.kt, core/common/src/main/kotlin/eu/kanade/tachiyomi/network/NetworkHelper.kt, core/common/src/main/kotlin/eu/kanade/tachiyomi/util/system/WebViewUtil.kt
- fix the webview detection in `getPackageName` to correctly detect it and return a spoofed package (thanks to @vetleledaal)
- spoofed package will be `com.android.chrome` (google chrome) or in some cases when it isn't installed, `com.android.settings`
- this needs to be a valid installed package, otherwise the app crashes 
- override `shouldInterceptRequest` of the webview to use okhttp for making the calls and being able to remove the header completely
- this isn't called for post or xhr/fetch calls in js so spoofed package name is needed 
closes #1659
=> Spoof or remove `X-Requested-With` header from webview

.github/workflows/build_push.yml
This will send a "app_release" event to the website repo to update it with the freshly published app version.
See also: https://github.com/mihonapp/mihon-preview/pull/34, https://github.com/mihonapp/website/pull/141
=> Update website when a new version is released

CHANGELOG.md, app/src/main/java/eu/kanade/presentation/track/TrackerSearch.kt, app/src/main/java/eu/kanade/presentation/track/TrackerSearchPreviewProvider.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/anilist/AnilistApi.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/anilist/dto/ALManga.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/anilist/dto/ALSearchItem.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/model/TrackSearch.kt
Include the artist and author information from anilist in the tracker search if available.
If all artists are the same as all authors it doesn't display artists.
Only thing i'm maybe concious of is that if ALL the info is there then it runs quite long and pushed the description quite low. Thought about putting the artist/authors on one row but don't think we have the space really.
But I think it's worth having this info on there.
I've put in a good amount of null protection cus I just don't know if those values are guaranteed from anilist query
=> Artist and author in track search info for anilist

CHANGELOG.md, app/src/main/java/eu/kanade/tachiyomi/ui/browse/migration/search/MigrateDialog.kt, domain/src/main/java/tachiyomi/domain/manga/interactor/GetLibraryManga.kt
Reopening #1794 due to #1799 having the possibility of OOM if the user's DB is astronomically large.
Fixes #93 
Cause is https://github.com/sqldelight/sqldelight/issues/1584 (and https://github.com/sqldelight/sqldelight/issues/4194 )
Similar to the implementation at https://github.com/jobobby04/TachiyomiSY/commit/3a5e23550ff0a1f5be7e03138f63ab4960716f82 and https://github.com/null2264/yokai/commit/50fecd5350c9e4aec04ff76c6849c331ca0d29ed but using 3x retries at 500ms each, 1500ms debounce, and a catch at the end as a "nothing worked but we don't want to crash" state.
Delay values/etc can be tweaked if needed.
=> Mitigate the libraryView NPE crash that occurs for large libraries when removing entries shortly after any other DB write

CHANGELOG.md, app/src/main/java/eu/kanade/tachiyomi/util/CrashLogUtil.kt
This will avoid the need to know which forks has which version numbers and avoid confusion in support.
Example output from the emulator:
```txt
App ID: app.mihon.dev
App version: 0.17.1-7136 (2ba2d86bf, 10, 2025-03-10T02:33:35Z)
Android version: 15 (SDK 35; build BP22.250124.008)
Device brand: google
Device manufacturer: Google
Device name: emu64xa (sdk_gphone64_x86_64)
Device model: sdk_gphone64_x86_64
WebView: Android System WebView 133.0.6943.138
Current time: 2025-03-10T02:34:20.257250Z
```
=> Add app ID to debug info

.github/workflows/build_push.yml, .github/workflows/update_website.yml
Follow up for #1818
See also: https://github.com/mihonapp/mihon-preview/pull/35
Why: the previous implementation didn't work properly because the build CI does only a draft release. This PR separates the website update into a separate workflow that is triggered whenever an actual release is published, deleted, or edited.
Also added --fail-with-body to curl so that the action fails when the event couldn't be sent successfully.
=> Rework website update workflow

CHANGELOG.md, app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryItem.kt
This prefix searches entries in the library based on the ID in the database. It is a niche feature but could be very helpful in certain situations, such as a corrupted cover causing a crash in Coil that just shows `🚨 Failed - MangaCover(mangaId=2245, sourceId=1, isMangaFavorite=true, url=, lastModified=0)`. With this prefix search it is possible to find the entry in question without much hassle.
Notably, the database includes literally anything Mihon has ever seen from extension and such, even if they weren't added to the collection. This means that IDs actually present in the collection are not expected to be purely sequential.
For example, in my emulator, I had two entries in the collection but the assigned IDs were 5 and 56.
=> Add prefix search to search by internal DB ID

.github/workflows/build_push.yml
Other wise, workflow would fail with this error:
```
Error: Couldnt find the Android build tools @ /usr/local/lib/android/sdk/build-tools/33.0.0
Error: Unable to locate executable file: /usr/local/lib/android/sdk/build-tools/33.0.0/zipalign. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```
=> Add back build tools for sign-android-release to be able to work

CHANGELOG.md
This should be the last "general CHANGELOG.md maintenance" we need. Future changes (direct commits and PRs) should be strongly encouraged to update the CHANGELOG.md file with their own contribution when they happen.
=> Add missing references to CHANGELOG.md

CHANGELOG.md, app/src/main/java/eu/kanade/tachiyomi/data/track/bangumi/BangumiApi.kt, app/src/main/java/eu/kanade/tachiyomi/data/track/bangumi/dto/BGMSearch.kt
Missed including this in the v0 rewrite.
Fixes #1880. The other part of the issue is a community translation issue or would require introducing a new string entirely.
=> Fix Bangumi search including novels

CHANGELOG.md, app/src/main/java/eu/kanade/tachiyomi/data/backup/BackupNotifier.kt, app/src/main/java/eu/kanade/tachiyomi/data/notification/NotificationReceiver.kt
Closes https://github.com/mihonapp/mihon/issues/1923
This pull request fixes an issue where tapping the "share" button in the backup complete notification does nothing when the app is in background.
Replaces `PendingIntent.getBroadcast()` with `PendingIntent.getActivity()` for the backup share notification action.
The previous implementation triggered a `BroadcastReceiver`, which attempted to launch the share activity via `getBroadcast()`. This fails when the app is backgrounded due to Android's restrictions on launching activities from background components.
Reference: [Android 10 – Background activity start restrictions](https://developer.android.com/about/versions/10/privacy/changes#background-activity-starts)
The updated implementation uses `getActivity()` to directly launch the share …
=> fix backup share not working from background notification

CHANGELOG.md, app/src/main/java/eu/kanade/presentation/components/AppBar.kt
Made all tooltips in AppBarAction non-focusable. Previously, tooltips would appear during hover while using mouse and block clicking on the icon. Additionally, on touch screen, after triggering tooltips via long-press, users had to dismiss them with another press before being able to interact with anything else.
=> Make AppBarAction tooltips non-focusable

CHANGELOG.md, app/src/main/java/eu/kanade/presentation/manga/components/MangaInfoHeader.kt, app/src/main/java/eu/kanade/presentation/manga/components/MarkdownRender.kt
Use `CommonMarkFlavourDescriptor` as a base and remove html & reference parsing to remove unwanted parsing of some types of texts
=> fix: simplify markdown parsing

CHANGELOG.md, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerPageHolder.kt, app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonPageHolder.kt
On image load error, pass source id to WebView via 'Open in WebView' to set proper headers.
=> Reader: set source headers in webview

app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderViewModel.kt
The condition for updating progress is wrong (`!=` to `is` instead of `!is`) since fefa8f84982b537ca930438f7976087844d5bb9c
This prevented progress to be actually updated, even when finishing chapters
=> Fix ReaderViewModel::updateChapterProgress

CHANGELOG.md, app/src/main/java/eu/kanade/presentation/browse/BrowseSourceScreen.kt
currently if using the "hide entries already in library" setting, it does not show an empty screen message or anything as it relies on the paging state error being no results error which doesn't happen if we filter them out afterwards due to the setting.
=> Empty browse source screen when hiding already added entried

CHANGELOG.md, app/src/main/java/eu/kanade/presentation/components/AppBar.kt, presentation-core/src/main/java/tachiyomi/presentation/core/util/Modifier.kt
On a physical/hardware keyboard, a keystroke sends two events. One of key press and one on key release, so effectively two events on a single keystroke. ([ref](https://developer.android.com/develop/ui/compose/touch-input/keyboard-input/commands#key_events))
This caused `searchAndClearFocus` in `SearchToolbar` composable to trigger twice, second time tapping the back button and exiting out of search.
To fix this, I have changed it to only trigger on Key release, which is the behavior of software keyboard when tapping the enter/search key.
Also changed it so focus is moved next, and not to the back button
Note: only tested on Waydroid, I don't know if this will have any other side effects on other devices with keyboards
closes #1131
=> Fix pressing `Enter` while searching also triggering navigation back on physical keyboards

CHANGELOG.md, core/common/src/main/kotlin/eu/kanade/tachiyomi/network/interceptor/CloudflareInterceptor.kt
Two changes:
1)
[`onReceivedError`](https://developer.android.com/reference/android/webkit/WebViewClient#onReceivedError(android.webkit.WebView,%20android.webkit.WebResourceRequest,%20android.webkit.WebResourceError)) doesn't give http error codes in the `error` parameter. It is instead some internal error code.
<details>
<summary>Ref</Summary>
https://developer.android.com/reference/android/webkit/WebResourceError#getErrorCode()
> Gets the error code of the error. The code corresponds to one of the ERROR_* constants in [WebViewClient](https://developer.android.com/reference/android/webkit/WebViewClient).
---
</details>
This means, `onPageFinish` will immediately call `latch.countDown()` (in last if block) as challenge was seemingly not found, without giving it some time. …
=> fix CloudflareInterceptor not waiting for the challenge

CHANGELOG.md, domain/src/main/java/tachiyomi/domain/manga/interactor/FetchInterval.kt, domain/src/test/java/tachiyomi/domain/manga/interactor/FetchIntervalTest.kt
this should make the smart updater less likely to be thrown off my long hiatuses
Relevant issues: #144
=> Use median instead of mean interval to estimate smart update interval

CHANGELOG.md, app/src/main/java/eu/kanade/presentation/browse/ExtensionsScreen.kt
Just adds the same word as the install option ("Private" in English) next to the extension version and 18+ label (if present).
Added this for my personal fork but thought it might be nice for others as well.
| Image 1 | Image 2 |
| ![](https://github.com/user-attachments/assets/08438d9c-ebaf-4505-9ad2-334316027df7) | ![](https://github.com/user-attachments/assets/a1d9f955-2b6d-473c-9f9c-5beed752d536) |
=> Add label to privately installed extensions

CHANGELOG.md, presentation-core/src/main/java/tachiyomi/presentation/core/components/VerticalFastScroller.kt
Fixes #1302
Fixes #1385.
The list scrollbar positioning code was reworked to correct for cases where there are irregularities in the scrolled item sizes. 
Scrollbar visibility was changed to be consistent throughout scrolling.
| Issue |  Fix  |
| ----- | ----- |
| <video src='https://github.com/user-attachments/assets/717e9243-6974-4fda-b395-b01d552abf79'> | <video src='https://github.com/user-attachments/assets/7e48bf3b-33ca-4955-8732-4f60847f105a'>|
| Issue |  Fix  |
| ----- | ----- |
| <video src='https://github.com/user-attachments/assets/649e3e31-b403-4d2f-8dae-3fae335ce5ac'> | <video src='https://github.com/user-attachments/assets/7012cab4-c3a3-44c9-8161-a8a4b441d17d'>|
=> Fix scrollbar display issues

CHANGELOG.md, app/src/main/java/eu/kanade/presentation/library/components/LibraryContent.kt
=> Fix 'Default' category showing in library with no user-added categories
