mihonapp/mihon

- i18n/src/commonMain/resources/MR/fi/strings.xml
Fix small grammatical errors in Finnish strings introduced by https://github.com/mihonapp/mihon/commit/653940613d661eb371aab3b3c3a8181e4e308c43
> Fix minor grammatical errors in Finnish strings

- i18n/src/commonMain/resources/MR/sr/plurals.xml
- i18n/src/commonMain/resources/MR/sr/strings.xml
Fixed some translations and added missing ones.
> Fixed Serbian translation

- app/src/main/java/eu/kanade/tachiyomi/data/backup/create/creators/MangaBackupCreator.kt
- app/src/main/java/eu/kanade/tachiyomi/data/backup/models/BackupManga.kt
- app/src/main/java/eu/kanade/tachiyomi/data/backup/restore/restorers/MangaRestorer.kt
Decided to not port the SY code and just make it from scratch since the implementations used different structures.
> Backup and Restore Excluded scanlators

- i18n/src/commonMain/resources/MR/zh-rTW/strings.xml
> Fix zh-rTW Translation

- i18n/src/commonMain/resources/MR/fil/strings.xml
Changed/updated a few grammatical strings for the Filipino Translation
Note:
- Some of the translations had to be updated for grammatical reasons or use a translation that is simple to understand.
> Update Filipino Strings

- i18n/src/commonMain/resources/MR/fil/plurals.xml
- i18n/src/commonMain/resources/MR/fil/strings.xml
- i18n/src/commonMain/resources/MR/fr/strings.xml
- i18n/src/commonMain/resources/MR/tr/strings.xml
- i18n/src/commonMain/resources/MR/zh-rTW/strings.xml
> Translations

- README.md
Also fix license and add disclaimer
Closes #199
> Change README to Markdown

- source-local/src/androidMain/kotlin/tachiyomi/source/local/LocalSource.kt
- source-local/src/androidMain/kotlin/tachiyomi/source/local/io/LocalSourceFileSystem.kt
> Fix extracting ComicInfo.xml files in local source

- app/src/main/java/eu/kanade/tachiyomi/ui/history/HistoryScreenModel.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/updates/UpdatesScreenModel.kt
- app/src/main/java/eu/kanade/tachiyomi/util/lang/DateExtensions.kt
- i18n/src/commonMain/resources/MR/base/plurals.xml
Tweaked header code to fix bug introduced in earlier timestamp fix
> Fix some issues from 7ff95e2

- app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsReaderScreen.kt
- app/src/main/java/eu/kanade/presentation/reader/settings/GeneralSettingsPage.kt
- app/src/main/java/eu/kanade/presentation/reader/settings/ReadingModePage.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/setting/ReaderPreferences.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonConfig.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonFrame.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonRecyclerView.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonViewer.kt
- i18n/src/commonMain/resources/MR/base/strings.xml
> Allow disabling reader's zoom out

- app/build.gradle.kts
- app/src/main/java/eu/kanade/presentation/webview/WebViewScreenContent.kt
- gradle/compose.versions.toml
- gradle/libs.versions.toml
Accompanist Webview has been deprecated, KevinZou (https://github.com/KevinnZou/compose-webview) has a fork that also is designed to support multiplatform.
> Migrated from Accompanist Webview to KevinZou WebView

- app/src/main/java/eu/kanade/domain/DomainModule.kt
- domain/src/main/java/mihon/domain/extensionrepo/interactor/CreateExtensionRepo.kt
> Fix extension repo crash with TypeReference issue

- app/build.gradle.kts
- app/src/main/java/eu/kanade/tachiyomi/App.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/main/MainActivity.kt
- app/src/main/java/mihon/core/migration/Migration.kt
- app/src/main/java/mihon/core/migration/MigrationCompletedListener.kt
- app/src/main/java/mihon/core/migration/MigrationContext.kt
- app/src/main/java/mihon/core/migration/MigrationJobFactory.kt
- app/src/main/java/mihon/core/migration/MigrationStrategy.kt
- app/src/main/java/mihon/core/migration/MigrationStrategyFactory.kt
- app/src/main/java/mihon/core/migration/Migrator.kt
- app/src/test/java/mihon/core/migration/MigratorTest.kt
Extracts the Migrator logic into separate classes to make it easier to test. And moves Migrator initialization to Application.
> Migrator improvements

- app/build.gradle.kts
- app/src/main/java/eu/kanade/presentation/browse/ExtensionDetailsScreen.kt
- app/src/main/java/eu/kanade/presentation/manga/components/ChapterDownloadIndicator.kt
- app/src/main/java/eu/kanade/presentation/manga/components/MangaBottomActionMenu.kt
- presentation-core/src/main/java/tachiyomi/presentation/core/components/AdaptiveSheet.kt
- presentation-core/src/main/java/tachiyomi/presentation/core/components/material/Surface.kt
- presentation-core/src/main/java/tachiyomi/presentation/core/util/Modifier.kt
Also remove a leftover of scoped storage adaptation.
> Use m3 ripple and clean up interactionSource usage

- app/src/main/java/eu/kanade/tachiyomi/App.kt
- app/src/main/java/eu/kanade/tachiyomi/data/coil/BufferedSourceFetcher.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/ReaderPageImageView.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerPageHolder.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/webtoon/WebtoonPageHolder.kt
- core/common/src/main/kotlin/tachiyomi/core/common/util/system/ImageUtil.kt
> Use Okio instead of `java.io` for image processing

- app/src/main/java/eu/kanade/domain/DomainModule.kt
- app/src/main/java/eu/kanade/domain/extension/interactor/TrustExtension.kt
- app/src/main/java/eu/kanade/tachiyomi/extension/ExtensionManager.kt
- app/src/main/java/eu/kanade/tachiyomi/extension/util/ExtensionInstallReceiver.kt
- app/src/main/java/eu/kanade/tachiyomi/extension/util/ExtensionLoader.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/extension/ExtensionsScreenModel.kt
> Trust extension by repo

- .github/workflows/build_pull_request.yml
- .github/workflows/build_push.yml
> Migrate to `gradle/actions/wrapper-validation`

- .github/workflows/build_pull_request.yml
- .github/workflows/build_push.yml
- app/src/test/java/mihon/core/migration/MigratorTest.kt
- Migrator test failed with error: No class found
- Build script hasn't been checking for it
> Fix Migrator test and also add the test to build script

- .github/workflows/build_pull_request.yml
- .github/workflows/build_push.yml
To decode obfuscated stack traces and help debugging R8 issues.
> Upload build artifacts

- app/src/main/java/eu/kanade/presentation/theme/colorscheme/NordColorScheme.kt
- presentation-core/src/main/res/values-night/colors_lavender.xml
- presentation-core/src/main/res/values-night/colors_midnightdusk.xml
- presentation-core/src/main/res/values-night/colors_nord.xml
- presentation-core/src/main/res/values-night/colors_tako.xml
- presentation-core/src/main/res/values/colors_lavender.xml
- presentation-core/src/main/res/values/colors_nord.xml
- presentation-core/src/main/res/values/colors_tako.xml
> Theme fixes

- README.md
| Before | After |
| ![image](https://github.com/mihonapp/mihon/assets/40583749/d8c1d418-d53d-49bb-8841-dccb23847a63) | ![image](https://github.com/mihonapp/mihon/assets/40583749/e49b7c00-e6b4-4bcf-92d7-b0bd7d8401de) |
> A Minor Milestone

- app/src/main/java/eu/kanade/tachiyomi/ui/webview/WebViewScreenModel.kt
> Don't crash on ill-formed URLs

- CONTRIBUTING.md
update Contributing info to use `detekt` instead of `ktLintFormat`.
> Contributing: ktLintFormat -> detekt

- .github/workflows/build_pull_request.yml
- .github/workflows/build_push.yml
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/mihon.android.application.compose.gradle.kts
- buildSrc/src/main/kotlin/mihon.android.application.gradle.kts
- buildSrc/src/main/kotlin/mihon.benchmark.gradle.kts
- buildSrc/src/main/kotlin/mihon.code.lint.gradle.kts
- buildSrc/src/main/kotlin/mihon.library.compose.gradle.kts
- buildSrc/src/main/kotlin/mihon.library.gradle.kts
- gradle/libs.versions.toml
> Add spotless (with ktlint)

- CHANGELOG.md
Adds references to the specific PR (or commit hash if no PR was made for the change) to the Changelog file.
> Add PR or commit refs to CHANGELOG.md

- app/src/main/java/eu/kanade/presentation/track/TrackerSearch.kt
Resolves #1126 
https://github.com/user-attachments/assets/00769ba1-fde4-4374-9b6b-94ceb3eb1f8e
> Hide keyboard when a Tracker SearchResultItem is clicked

- core/archive/src/main/kotlin/mihon/core/archive/UniFileExtensions.kt
> `spotlessApply` my beloved

- gradle/libs.versions.toml
> Use uy.kohesive.injekt instead of com.github.inorichi.injekt

- app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsSearchScreen.kt
- app/src/main/java/eu/kanade/presentation/track/TrackerSearch.kt
- app/src/main/java/eu/kanade/presentation/track/TrackerSearchPreviewProvider.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/track/TrackInfoDialog.kt
- presentation-core/src/main/java/tachiyomi/presentation/core/components/WheelPicker.kt
> Use TextFieldState in BasicTextField where applicable

- buildSrc/src/main/kotlin/mihon/buildlogic/AndroidConfig.kt
> Bump NDK version

- app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsAdvancedScreen.kt
> Show toast for app restart when User-Agent is changed

- presentation-core/src/main/java/tachiyomi/presentation/core/components/WheelPicker.kt
Resolves #1147 
Previously - Manual Input just doesn't work.
Now
- Manual Input works if the user press `Done` on the keyboard.
- Cant get it to work if the user presses back and closes the keyboard without pressing done
Either way better than it was before
> Fix WheelPicker Manual Input

- app/src/main/java/eu/kanade/presentation/util/ExceptionFormatter.kt
- i18n/src/commonMain/moko-resources/base/strings.xml
- source-api/src/commonMain/kotlin/eu/kanade/tachiyomi/source/online/HttpSource.kt
Resolves #1199 
5ae0589547489193826b6205f05711a07ceaa16b <- Commit for reference
> Re-enable fetching chapters list for entries with licenced status

- app/src/main/java/eu/kanade/tachiyomi/data/backup/create/BackupCreator.kt
- app/src/main/java/eu/kanade/tachiyomi/data/backup/create/BackupOptions.kt
- data/src/main/java/tachiyomi/data/manga/MangaRepositoryImpl.kt
- data/src/main/sqldelight/tachiyomi/data/mangas.sq
- domain/src/main/java/tachiyomi/domain/manga/repository/MangaRepository.kt
- i18n/src/commonMain/moko-resources/base/strings.xml
Fixes #4
https://github.com/jobobby04/TachiyomiSY/commit/e633da5567e6cc33beff1757d50c55b7e729a644
https://github.com/jobobby04/TachiyomiSY/commit/65f66630cfdd67fd6af00fe3a63dc117651e9d5f
https://github.com/jobobby04/TachiyomiSY/commit/8b777e1e5a177babdac1420f20db1f5139302f0d
> Add option to backup non-library read entries

- i18n/README.md
Path was outdated and the info had a typo.
> Update i18n readme

- app/src/main/java/eu/kanade/domain/track/service/TrackPreferences.kt
- app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsTrackingScreen.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaScreenModel.kt
- i18n/src/commonMain/moko-resources/base/strings.xml
> Rework Auto Track on Mark as Read

- app/src/main/java/eu/kanade/domain/track/model/AutoTrackState.kt
- app/src/main/java/eu/kanade/domain/track/service/TrackPreferences.kt
- app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsTrackingScreen.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaScreenModel.kt
Fixes #1369 
Switches preference to Enum.
Switches setting from switch to list.
> Allow Disabling Auto Track on Mark as Read & Fix #1369

- app/src/main/java/eu/kanade/presentation/library/components/LibraryTabs.kt
https://github.com/user-attachments/assets/c015f583-c324-4926-825a-b01f76b0ec49
> Fix crash when delete last category while library being on that category

- .editorconfig
- buildSrc/src/main/kotlin/mihon.code.lint.gradle.kts
> Add more editor configs and move ktlint config to it

- CHANGELOG.md
- app/src/main/java/eu/kanade/presentation/history/HistoryScreen.kt
- app/src/main/java/eu/kanade/presentation/history/components/HistoryItem.kt
- app/src/main/java/eu/kanade/presentation/manga/components/MangaCover.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/history/HistoryScreenModel.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/history/HistoryTab.kt
closes #1654
Basically that minus the badge ⬇️
https://github.com/user-attachments/assets/d74d75cc-ff05-428a-b31b-6d28ace2569f
> Add an `Add to Favorites` button on HistoryScreen

- CHANGELOG.md
- app/src/main/java/eu/kanade/tachiyomi/data/track/kitsu/Kitsu.kt
- app/src/main/java/eu/kanade/tachiyomi/data/track/kitsu/KitsuApi.kt
- app/src/main/java/eu/kanade/tachiyomi/data/track/kitsu/dto/KitsuListSearch.kt
Yes it was this simple apparently.
Tried the following:
> Add private tracking support for Kitsu

- app/src/main/java/eu/kanade/presentation/more/onboarding/PermissionStep.kt
> Don't show divider when analytics is not included

- .github/workflows/build_push.yml
- buildSrc/src/main/kotlin/mihon/buildlogic/AndroidConfig.kt
- buildSrc/src/main/kotlin/mihon/buildlogic/ProjectExtensions.kt
this is beneficial to reproduce the build environment as official
> add BUILD_TOOLS_VERSION to buildlogic

- .github/ISSUE_TEMPLATE/report_issue.yml
I have no idea how to check for issue template, but formatting should be the same
> Update Issue Request Template

- CHANGELOG.md
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaScreenModel.kt
Fixes #1793 
Fixes #1522 
https://github.com/mihonapp/mihon/issues/1522 was basically fixed already but his should make sure that it doesn't happen
> Refresh Trackers Before Overwriting Remote

- .github/workflows/build_push.yml
- app/build.gradle.kts
- app/src/main/java/eu/kanade/presentation/more/settings/screen/about/AboutScreen.kt
- app/src/main/java/eu/kanade/tachiyomi/data/updater/AppUpdateChecker.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/main/MainActivity.kt
- app/src/main/java/eu/kanade/tachiyomi/util/system/BuildConfig.kt
- Remove `BuildConfig.PREVIEW`
- Rename `BuildConfig.INCLUDE_ANALYTICS` -> `BuildConfig.ANALYTICS_INCLUDED`
- Rename `BuildConfig.INCLUDE_UPDATER` -> `BuildConfig.UPDATER_ENABLED`
- Rename build property `with-analytics` -> `include-analytics`
- Rename build property `with-updater` -> `enable-updater`
- Add build property to disable code shrink
- Add build property to include dependency info in apk/app bundle
> Change foss variant application id suffix to '.foss' and more

- CHANGELOG.md
- app/src/main/java/eu/kanade/domain/chapter/interactor/SyncChaptersWithSource.kt
- app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsLibraryScreen.kt
- app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsReaderScreen.kt
- app/src/main/java/eu/kanade/tachiyomi/data/database/models/Chapter.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/ReaderViewModel.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/setting/ReaderPreferences.kt
- domain/src/main/java/tachiyomi/domain/library/service/LibraryPreferences.kt
- i18n/src/commonMain/moko-resources/base/strings.xml
> Change option to mark duplicate chapter as read apply when reading

- CHANGELOG.md
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerViewer.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerViewerAdapter.kt
Adapted from TachiyomiSY
Closes #875
> Fix next chapter button not changing chapter

- CHANGELOG.md
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/viewer/pager/PagerViewer.kt
> Fix page number not appearing when opening chapter

- CHANGELOG.md
- app/src/main/java/eu/kanade/presentation/manga/components/MarkdownRender.kt
- app/src/main/java/eu/kanade/presentation/more/NewUpdateScreen.kt
- gradle/libs.versions.toml
> Update markdown to 0.33.0 + small fixes

- CHANGELOG.md
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/browse/BrowseSourceScreen.kt
> Fix content under source browse screen top appbar is interactable

- CHANGELOG.md
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/browse/SourceFilterDialog.kt
> Fix crash when trying use source sort filter without a pre-selection

- CHANGELOG.md
- core/common/src/main/kotlin/eu/kanade/tachiyomi/network/NetworkPreferences.kt
> Switch default user agent to Android Chrome

- CHANGELOG.md
- app/src/main/java/eu/kanade/tachiyomi/ui/reader/setting/ReaderPreferences.kt
> Disable reader's 'Keep screen on' setting by default

- app/src/main/java/eu/kanade/presentation/library/components/LibraryContent.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryScreenModel.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryTab.kt
> Potentially fix library `IndexOutOfBound` crash

- CHANGELOG.md
- core/archive/src/main/kotlin/mihon/core/archive/EpubReader.kt
> Fix local source EPUB files not loading

- app/src/main/java/eu/kanade/presentation/more/settings/screen/browse/components/ExtensionReposDialogs.kt
- app/src/main/java/eu/kanade/tachiyomi/data/download/Downloader.kt
- i18n/src/commonMain/moko-resources/base/strings.xml
Since this doesn't really affect Mihon but forks, idk if you want a changelog entry.
> Don't hardcode app name in `strings.xml`

- app/src/main/java/eu/kanade/presentation/manga/components/MarkdownRender.kt
- gradle/libs.versions.toml
> Update markdown to 0.37.0

- CHANGELOG.md
- app/src/main/java/eu/kanade/tachiyomi/App.kt
> Fix click to disable incognito mode notification
